/**
 * default setting
 */

module.exports = exports.default = {
  hotkey: 'Control+2',
  sshReadyTimeout: 50000,
  scrollback: 3000,
  onStartSessions: [],
  fontSize: 16,
  fontFamily: 'Maple Mono, mono, courier-new, courier, monospace',
  execWindows: 'System32/WindowsPowerShell/v1.0/powershell.exe',
  execMac: 'zsh',
  execLinux: 'bash',
  execWindowsArgs: [],
  execMacArgs: [],
  execLinuxArgs: [],
  enableGlobalProxy: false,
  disableConnectionHistory: false,
  disableTransferHistory: false,
  terminalBackgroundImagePath: '',
  terminalBackgroundFilterOpacity: 1,
  terminalBackgroundFilterBlur: 0,
  terminalBackgroundFilterBrightness: 1,
  terminalBackgroundFilterGrayscale: 0,
  terminalBackgroundFilterContrast: 1,
  rendererType: 'dom',
  terminalType: 'xterm-256color',
  keepaliveCountMax: 10,
  saveTerminalLogToFile: false,
  cursorBlink: false,
  cursorStyle: 'block',
  useSystemTitleBar: false,
  opacity: 1,
  defaultEditor: '',
  terminalWordSeparator: './\\()"\'-:,.;<>~!@#$%^&*|+=[]{}`~ ?',
  confirmBeforeExit: false,
  initDefaultTabOnStart: true,
  screenReaderMode: false,
  autoRefreshWhenSwitchToSftp: false,
  addTimeStampToTermLog: false,
  keepaliveInterval: 10000,
  backspaceMode: '^?',
  shiftEnterMode: '\\n',
  showHiddenFilesOnSftpStart: true,
  terminalInfos: [
    'uptime',
    'cpu',
    'mem',
    'dockers',
    'activities',
    'network',
    'disks'
  ],
  filePropsEnabled: [
    'name',
    'size',
    'modifyTime'
  ],
  hideIP: false,
  dataSyncSelected: 'all',
  nameAI: '',
  baseURLAI: 'https://api.deepseek.com/v1',
  modelAI: 'deepseek-chat',
  roleAI: '终端专家,提供不同系统下命令,简要解释用法,用markdown格式',
  apiPathAI: '/chat/completions',
  authHeaderNameAI: 'Authorization: Bearer',
  proxyAI: '',
  aiBackendType: 'openai_compatible',
  codexProfileId: '',
  codexAppServerExecutable: '',
  agentModeEnabled: false,
  agentMutationEnabled: false,
  agentExternalMcpEnabled: false,
  agentRuntimeV2RolloutStage: 8,
  agentProviderStreamingV2: true,
  agentExecutionOutputProgressV2: true,
  agentPersistentProviderSessionV2: true,
  agentGroundedFinalSynthesisV2: true,
  agentReadProbeBundleV2: true,
  agentModelProfilesV2: true,
  agentSkillsV2: true,
  agentKnowledgeBaseV2: true,
  agentGroundedSynthesisEnabled: true,
  agentFastModel: '',
  agentPlannerModel: '',
  agentSummarizerModel: '',
  agentMaxContextTokens: 32000,
  agentMaxOutputTokens: 2048,
  agentModelTimeoutMs: 30000,
  agentSynthesisTimeoutMs: 15000,
  agentStreamingEnabled: true,
  agentStructuredMode: 'native-tools',
  agentReasoningEffort: 'medium',
  agentTemperature: 0.2,
  agentPromptCacheEnabled: true,
  agentSkillsEnabled: true,
  agentSkillDirectories: '',
  agentKnowledgeEnabled: false,
  agentKnowledgeSources: '',
  agentKnowledgeEmbeddingMode: 'off',
  agentCapabilityLevel: '',
  agentCapabilityCheckedAt: '',
  agentCapabilityExpiresAt: '',
  agentCapabilityProfileHash: '',
  sessionLogPath: '',
  sshSftpSplitView: false,
  showCmdSuggestions: false,
  startDirectoryLocal: '',
  allowMultiInstance: false,
  disableDeveloperTool: false,
  dragDropBehavior: 'ask',
  switchTabOnHover: false
}
